version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - '8080:80'
    volumes:
      - .:/app/
    links:
      - php
    networks:
      - wdpai-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/
    networks:
      - wdpai-network

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - '5433:5432'
    networks:
      - pg-network
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: w2wwizard@gmail.com
      PGADMIN_DEFAULT_PASSWORD: adminhaslo
    ports:
      - '5050:80'
    networks:
      - pg-network

networks:
  wdpai-network:
  pg-network:

volumes:
  pg-data:
