<?php

Class Activities{
    public function getActivitiesBelowZero(): array
    {
        return [
            'Ice skating',
            'Skiing',
            'Snowboarding',
            'Snowshoeing',
            'Winter hiking',
            'Ice fishing',
            'Snowmobiling',
            'Curling',
            'Ice hockey',
            'Figure skating',
            'Snow sculpting',
            'Dog sledding',
            'Ice climbing',
            'Bobsledding',
            'Cross-country skiing',
            'Snow tubing',
            'Biathlon',
            'Ice fishing derby',
            'Winter camping',
            'Snowmobiling tour',
            'Frozen waterfall climbing',
            'Sled dog race',
            'Snowcat skiing',
            'Ice sailing',
            'Ice diving',
            'Ice karting',
            'Snowkiting',
            'Ice boating',
            'Pond hockey',
            'Ice luge',
            'Ice hotel stay',
            'Northern lights viewing',
            'Ice cave exploration',
            'Snow golf',
            'Ice stock sport',
            'Winter survival training',
            'Ice sculpture festival',
            'Polar bear plunge',
            'Ice archery',
            'Snowmobile ice drag racing',
            'Snow polo',
            'Ice fishing hut construction',
            'Aurora photography',
            'Frozen lake walk',
            'Ice wine tasting',
            'Winter bird watching',
            'Snow maze navigation',
            'Icebreaker ship tour',
            'Frozen river kayaking'
        ];
    }

    public function getActivitiesZeroToTenDegrees(): array
    {
        return [
            'Tennis',
            'Golf',
            'Yoga',
            'Fitness',
            'Indoor cycling',
            'Jump rope',
            'Table tennis',
            'Badminton',
            'Pilates',
            'Walking',
            'Jogging',
            'Hiking',
            'Biking',
            'Outdoor fitness class',
            'Rock climbing',
            'Fishing',
            'Canoeing',
            'Kayaking',
            'Archery',
            'Gardening',
            'Parkour',
            'Crossfit',
            'Rowing',
            'Softball',
            'Baseball',
            'Soccer',
            'Basketball',
            'Volleyball',
            'Handball',
            'Ultimate frisbee',
            'Disc golf',
            'Skateboarding',
            'Rollerblading',
            'Sailing',
            'Camping',
            'Picnicking',
            'Geocaching',
            'Nature walk',
            'Bird watching',
            'Outdoor photography',
            'Stargazing',
            'Yard work',
            'Paintball',
            'Shuffleboard',
            'Petanque',
            'Trampolining',
            'Frisbee golf',
            'Horseshoes',
            'Tai Chi'
        ];
    }

    public function getActivitiesTenToTwentyDegrees(): array
    {
        return [
            'Running',
            'Cycling',
            'Soccer',
            'Basketball',
            'Volleyball',
            'Tennis',
            'Hiking',
            'Climbing',
            'Frisbee',
            'Badminton',
            'Softball',
            'Baseball',
            'Golf',
            'Skateboarding',
            'Rollerblading',
            'Parkour',
            'Rowing',
            'Canoeing',
            'Kayaking',
            'Archery',
            'Fishing',
            'Outdoor fitness class',
            'Yoga',
            'Pilates',
            'Tai Chi',
            'Crossfit',
            'Boxing',
            'Martial arts training',
            'Ultimate frisbee',
            'Disc golf',
            'Handball',
            'Beach volleyball',
            'Surfing',
            'Paddleboarding',
            'Kayak polo',
            'Rock climbing',
            'Mountain biking',
            'Trail running',
            'Outdoor boot camp',
            'Obstacle course race',
            'Geocaching',
            'Nature photography',
            'Bird watching',
            'Picnicking',
            'Outdoor painting',
            'Outdoor yoga class',
            'Stargazing',
            'Lawn games',
            'Horseback riding',
            'Hiking with a dog'
        ];
    }

    public function getActivitiesTwentyToThirtyDegrees(): array
    {
        return [
            'Swimming',
            'Surfing',
            'Water skiing',
            'Wakeboarding',
            'Yoga',
            'Beach volleyball',
            'Kayaking',
            'Paddleboarding',
            'Snorkeling',
            'Beach soccer',
            'Beach frisbee',
            'Beach paddleball',
            'Sailing',
            'Canoeing',
            'Jet skiing',
            'Windsurfing',
            'Kiteboarding',
            'Water aerobics',
            'Scuba diving',
            'Tubing',
            'Rowing',
            'Fishing',
            'Hiking',
            'Cycling',
            'Running',
            'Volleyball',
            'Soccer',
            'Tennis',
            'Outdoor yoga class',
            'Pilates',
            'Outdoor fitness class',
            'Rock climbing',
            'Trail running',
            'Mountain biking',
            'Camping',
            'Picnicking',
            'Outdoor concert',
            'Festival',
            'Fishing trip',
            'Bird watching',
            'Nature photography',
            'Geocaching',
            'Stand-up paddleboarding',
            'Beachcombing',
            'Lawn games',
            'Outdoor cooking class',
            'Beer tasting',
            'Sunset watching'
        ];
    }

    public function getActivitiesFromThirtyDegrees(): array {
        return [
            'Swimming',
            'Surfing',
            'Water skiing',
            'Wakeboarding',
            'Yoga',
            'Beach volleyball',
            'Kayaking',
            'Paddleboarding',
            'Snorkeling',
            'Beach soccer',
            'Beach frisbee',
            'Beach paddleball',
            'Sailing',
            'Canoeing',
            'Jet skiing',
            'Windsurfing',
            'Kiteboarding',
            'Water aerobics',
            'Scuba diving',
            'Tubing',
            'Rowing',
            'Fishing',
            'Hiking',
            'Cycling',
            'Running',
            'Volleyball',
            'Soccer',
            'Tennis',
            'Outdoor yoga class',
            'Pilates',
            'Outdoor fitness class',
            'Rock climbing',
            'Trail running',
            'Mountain biking',
            'Camping',
            'Picnicking',
            'Outdoor concert',
            'Festival',
            'Fishing trip',
            'Bird watching',
            'Nature photography',
            'Geocaching',
            'Stand-up paddleboarding',
            'Beachcombing',
            'Lawn games',
            'Outdoor cooking class',
            'Beer tasting',
            'Sunset watching'
        ];
    }

    public function getActivitiesForRainyWeather(): array{
        return [
            'Indoor rock climbing',
            'Bowling',
            'Indoor basketball',
            'Trampoline park',
            'Cooking or baking class',
            'Indoor swimming',
            'Indoor soccer',
            'Virtual workout class',
            'Board game marathon',
            'Movie marathon at home',
            'Learning a new musical instrument',
            'DIY home improvement project',
            'Puzzle-solving session',
            'Virtual tour of historical sites',
            'Virtual art class',
            'Starting a journal or blog',
            'Virtual dance class',
            'Meditation or yoga',
            'Indoor gardening',
            'Spa day at home',
            'Reading a good book',
            'Virtual cooking class',
            'Virtual concert or live-streamed performance',
            'Indoor photography',
            'Online language course',
            'Virtual book club',
            'DIY home decor project',
            'Virtual escape room',
            'Online gaming marathon',
            'Virtual trivia night',
            'Online workout challenge',
            'Virtual board games with friends',
            'Indoor cycling class',
            'Virtual museum or art gallery visit',
            'Cooking up new recipes',
            'Virtual fitness challenge',
            'DIY crafting or knitting',
            'Online meditation group',
            'Virtual reality gaming',
            'Indoor trampolining',
            'Learning a new language online',
            'Virtual karaoke night',
            'Virtual movie night with friends',
            'Indoor ice skating',
            'Online puzzle challenges',
            'Virtual DIY beauty workshop',
            'Joining an online support group',
            'Virtual science experiments at home',
            'Indoor archery',
        ];
    }

    public function getMessagesBelowZero(): array
    {
        return [
            'Brrr! Bundle up and enjoy the winter wonderland with some ice skating.',
            'Embrace the cold! Try your hand at skiing or snowboarding for an exhilarating experience.',
            'Snowy days are perfect for snowshoeing adventures. Explore the serene winter landscapes.',
            'Challenge the frosty breeze with some winter hiking. Don’t forget your thermos of hot cocoa!',
            'Ice fishing can be a relaxing and rewarding winter activity. Find a frozen lake and enjoy the tranquility.',
            'Experience the thrill of snowmobiling through snowy trails. Adventure awaits!',
            'Get competitive with a game of curling on the icy rink. Sweep your way to victory!',
            'Feel the adrenaline rush with some ice hockey. Skate, shoot, and score!',
            'Master the art of figure skating and glide gracefully across the ice.',
            'Try your hand at snow sculpting. Create your own winter masterpiece!',
            'Discover the joy of dog sledding. Let the furry companions lead you through the snowy landscapes.',
            'Climb to new heights with ice climbing. Challenge yourself with frozen waterfalls.',
            'Experience the speed of bobsledding. Feel the G-force as you navigate the icy track.',
            'Enjoy the beauty of winter landscapes with cross-country skiing. A great workout in the snow!',
            'Feel the thrill of snow tubing down snowy hills. It’s like sledding, but with extra excitement!',
            'Combine skiing and shooting skills with biathlon. Test your precision in the winter sports arena.',
            'Join an ice fishing derby and compete with fellow anglers for the biggest catch!',
            'Embark on a winter camping trip. Embrace the cold and connect with nature.',
            'Explore the winter wonderland with a snowmobile tour. Discover hidden trails and scenic spots.',
            'Climb frozen waterfalls with ice climbing. It’s a challenging adventure for the brave!',
            'Join a sled dog race and experience the excitement of mushing through snowy trails.',
            'Capture the magic of winter with outdoor ice sculpture festivals. Marvel at the intricate designs!',
            'Stay warm and enjoy icebreaker ship tours. Learn about the unique features of ice-covered waters.',
            'Test your skills with ice luge. Speed down the icy track for an adrenaline-pumping experience.',
            'Challenge friends to a game of pond hockey. Skates on, sticks ready, and score some goals!',
            'Indulge in winter survival training. Learn essential skills for outdoor adventures in the cold.',
            'Join the fun of ice fishing hut construction. Build your shelter and enjoy ice fishing in comfort.',
            'Experience the excitement of snowmobiling ice drag racing. Feel the speed on frozen lakes!',
            'Get creative with snow sculptures. Organize a neighborhood competition and showcase your artistry.',
            'Join a winter bird watching expedition. Spot unique species that thrive in cold weather.',
            'Explore the beauty of ice caves. Marvel at the stunning formations created by nature.',
            'Take a polar bear plunge for a refreshing and invigorating experience. Brave the cold waters!',
            'Hone your archery skills in the crisp winter air. Experience the precision of cold-weather target practice.',
            'Enjoy the thrill of snowcat skiing. Traverse untracked powder for an unforgettable skiing adventure.',
            'Experience the excitement of a snowmobile ice drag race. Feel the speed on icy tracks!',
            'Stay warm with a cup of hot cocoa after an adventurous day of ice fishing. Cozy up by the fire.',
            'Participate in a snow polo match. Ride horses through the snow and compete in this unique sport.',
            'Join a winter beer tasting event. Sample seasonal brews and enjoy the cold weather festivities.',
            'Capture the beauty of winter landscapes with outdoor photography. Create lasting memories!',
            'Stay active with snowshoe races. Race through snowy trails for a fun and challenging workout.',
            'Join a winter geocaching adventure. Discover hidden treasures in the snow-covered wilderness.',
            'Experience the thrill of snowmobiling through forested trails. Enjoy the winter scenery on a speedy ride.',
            'Celebrate winter with an outdoor festival. Enjoy live music, food, and entertainment in the snow.',
            'Challenge yourself with snowmobiling jumps. Catch some air and experience the thrill of the snow!',
        ];
    }

    public function getMessagesZeroToTenDegrees(): array
    {
        return [
            'Enjoy the cool weather with a game of tennis. It’s a great way to stay active!',
            'Golf is perfect in this weather. Enjoy the greenery and a round of golf.',
            'Table tennis is a fast-paced indoor activity. Grab a paddle and challenge a friend!',
            'Badminton is a great way to stay active indoors. Grab a racket and have some fun!',
            'Pilates is perfect for toning muscles and improving flexibility. Give it a try!',
            'Take a brisk walk in the crisp air. It’s a simple yet effective way to stay active.',
            'Jogging is a fantastic way to enjoy the cool weather and boost your mood.',
            'Hiking is wonderful in this weather. Enjoy the fresh air and beautiful scenery.',
            'Biking is a great way to explore the outdoors. Take a ride and enjoy the cool breeze.',
            'Join an outdoor fitness class. It’s a fun way to stay fit and connect with others.',
            'Indoor rock climbing is a thrilling activity. Challenge yourself on the climbing wall!',
            'Try your luck at fishing. Cooler temperatures can make for a peaceful fishing experience.',
            'Canoeing in moderate weather is a delightful way to explore lakes and rivers.',
            'Kayaking is a great upper-body workout. Enjoy the tranquility of paddling on calm waters.',
            'Archery is a precise and focused activity. Test your aim in this enjoyable sport.',
            'Engage in some gardening. The cool weather is perfect for tending to your plants.',
            'Explore the urban landscape with parkour. It’s a dynamic and exciting form of movement.',
            'Crossfit workouts are intense and effective. Challenge yourself with a high-intensity session.',
            'Rowing is an excellent full-body workout. Head to a nearby lake for a peaceful row.',
            'Play a game of softball with friends. It’s a great way to enjoy the outdoors and socialize.',
            'Baseball is a classic sport for a reason. Grab a glove and enjoy a friendly game.',
            'Soccer is a fantastic team sport. Gather friends for a game and enjoy the cool weather.',
            'Basketball is a dynamic and fast-paced sport. Shoot some hoops and break a sweat.',
            'Volleyball is a fun and social sport. Set up a net and enjoy a game with friends.',
            'Handball is an energetic team sport. Gather a group and have a friendly match.',
            'Ultimate frisbee is a great way to stay active and enjoy the outdoors. Give it a toss!',
            'Disc golf is a laid-back outdoor activity. Challenge friends to a round of disc golf.',
            'Skateboarding is a cool way to stay active. Cruise around and enjoy the cool breeze.',
            'Rollerblading is a fun and nostalgic activity. Glide through the neighborhood and have fun.',
            'Sailing is a serene water activity. Head to a lake and enjoy a peaceful sail.',
            'Camping in cool weather is refreshing. Set up a tent and enjoy the great outdoors.',
            'Picnicking in moderate temperatures is delightful. Pack a meal and enjoy nature.',
            'Geocaching is an adventurous outdoor activity. Go on a treasure hunt with your GPS!',
            'Take a nature walk in the cool weather. Enjoy the beauty of the outdoors.',
            'Bird watching is a calming outdoor hobby. Spot different species and enjoy nature.',
            'Capture the beauty of the outdoors with outdoor photography. Explore and take stunning shots.',
            'Stargazing is enchanting in cool weather. Grab a telescope and admire the night sky.',
            'Yard work is a productive way to stay active. Tend to your garden and enjoy the outdoors.',
            'Try paintball for an adrenaline-pumping outdoor activity. Challenge friends to a match!',
            'Shuffleboard is a laid-back outdoor game. Gather friends and enjoy some friendly competition.',
            'Petanque is a classic outdoor game. It’s easy to learn and fun to play.',
            'Trampolining is a joyful way to stay active. Bounce around and have a great time.',
            'Frisbee golf combines frisbee throwing and golf. Navigate the course and have fun.',
            'Horseshoes is a classic outdoor game. Set up a horseshoe pit and play with friends.',
            'Engage in a Tai Chi session for relaxation and gentle exercise. Enjoy the soothing movements.',
        ];
    }

    public function getMessagesTenToTwentyDegrees(): array
    {
        return [
            'Go for a run in the crisp and refreshing air. It’s the perfect temperature for outdoor jogging.',
            'Hop on your bike and enjoy a leisurely ride in the moderate weather. Explore the surroundings.',
            'Kick a soccer ball around with friends. The cool breeze makes it an enjoyable game.',
            'Shoot some hoops on an outdoor basketball court. The mild weather is perfect for a game.',
            'Volleyball on the beach is a great way to stay active. Feel the sand between your toes.',
            'Tennis is a fantastic sport in moderate temperatures. Grab a racket and hit the court.',
            'Take a scenic hike in the moderate weather. Enjoy the beauty of nature and the cool air.',
            'Try your hand at rock climbing. The moderate temperature makes it an ideal outdoor activity.',
            'Frisbee is a fun and social activity. Gather friends for a game in the pleasant weather.',
            'Badminton is a great way to stay active outdoors. Set up a net and enjoy a friendly match.',
            'Play a game of softball in the comfortable weather. Gather friends for a casual game.',
            'Golf is a classic outdoor activity. Enjoy a round of golf in the pleasant temperatures.',
            'Skateboarding is enjoyable in moderate weather. Cruise around and practice your tricks.',
            'Rollerblading is a fun and nostalgic activity. Glide through the neighborhood in comfort.',
            'Sailing is a serene water activity. Head out to sea or a lake and enjoy the mild breeze.',
            'Canoeing is a relaxing way to explore waterways. Paddle along and take in the scenery.',
            'Go kayaking on a calm river or lake. It’s a great way to enjoy the outdoors.',
            'Archery is a precise and focused outdoor activity. Test your aim in the comfortable weather.',
            'Take up fishing as a peaceful outdoor hobby. Find a quiet spot and cast your line.',
            'Join an outdoor fitness class. It’s a fun way to stay fit and enjoy the mild weather.',
            'Yoga in the park is a rejuvenating experience. Connect with nature and find inner peace.',
            'Pilates is perfect for toning muscles in comfortable weather. Enjoy a session outdoors.',
            'Tai Chi in the open air is a calming way to exercise both the body and mind.',
            'Crossfit workouts are intense and effective. Challenge yourself with a session in moderate temperatures.',
            'Rowing on a calm lake is a peaceful outdoor activity. Enjoy the rhythmic motion.',
            'Engage in some outdoor cross-country running. Enjoy the trails and the mild weather.',
            'Go for a bike ride through scenic routes. Feel the wind in your hair and enjoy the ride.',
            'Join a pick-up game of soccer. The moderate weather is ideal for some friendly competition.',
            'Basketball is a dynamic and fast-paced sport. Shoot some hoops in the comfortable weather.',
            'Volleyball is a fun and social sport. Set up a net and enjoy a game with friends.',
            'Handball is an energetic team sport. Gather a group and have a friendly match outdoors.',
            'Ultimate frisbee is a great way to stay active and socialize. Enjoy the pleasant weather.',
            'Disc golf is a laid-back outdoor activity. Challenge friends to a round of disc golf.',
            'Skateboarding is a cool way to stay active. Cruise around and enjoy the comfortable breeze.',
            'Rollerblading is a fun and nostalgic activity. Glide through the neighborhood in the mild weather.',
            'Parkour is an exciting and dynamic outdoor movement. Explore urban landscapes with agility.',
            'Join an outdoor fitness class. It’s a fun way to stay fit and connect with others.',
            'Take up outdoor climbing for a thrilling experience. Challenge yourself on the climbing wall.',
            'Explore the beauty of nature with trail running. Enjoy the trails in the moderate weather.',
            'Mountain biking is a thrilling outdoor activity. Navigate challenging terrains and enjoy the ride.',
            'Join an outdoor boot camp for a full-body workout. Sweat it out in the open air.',
            'Participate in an obstacle course race. Test your strength and agility in the moderate weather.',
            'Geocaching is an adventurous outdoor activity. Go on a treasure hunt with your GPS!',
            'Nature photography is a creative way to enjoy the outdoors. Capture the beauty around you.',
            'Bird watching is a calming outdoor hobby. Spot different species and enjoy nature.',
            'Picnicking in moderate temperatures is delightful. Pack a meal and enjoy nature.',
            'Outdoor painting is a creative way to connect with nature. Capture the beauty on your canvas.',
            'Enjoy a live outdoor concert in the comfortable weather. Listen to music under the open sky.',
        ];
    }

    public function getMessagesTwentyToThirtyDegrees(): array
    {
        return [
            'Cool off with a refreshing swim in the pool. It’s the perfect way to beat the heat.',
            'Surfing is a thrilling water sport. Catch some waves and enjoy the sunshine.',
            'Water skiing is an exciting water activity. Feel the rush as you glide across the water.',
            'Try wakeboarding for an adrenaline-pumping experience on the water.',
            'Yoga in the sunshine is invigorating. Connect with nature as you practice your poses.',
            'Beach volleyball is a fun and social activity. Gather friends for a game on the sand.',
            'Kayaking on calm waters is a peaceful way to enjoy the outdoors. Paddle along and relax.',
            'Paddleboarding is a great full-body workout. Stand on the board and enjoy the water.',
            'Snorkeling is a fascinating way to explore underwater worlds. Dive in and discover the beauty.',
            'Beach soccer is a lively and fun sport. Kick the ball around on the sandy shores.',
            'Beach frisbee is a relaxed way to enjoy the beach. Toss the frisbee and have fun.',
            'Beach paddleball is a great beachside activity. Grab a paddle and enjoy a game in the sun.',
            'Sailing in warm weather is delightful. Feel the breeze as you navigate the open waters.',
            'Canoeing in sunny weather is a peaceful outdoor activity. Paddle along and enjoy the scenery.',
            'Jet skiing is an exhilarating water sport. Feel the speed as you zoom across the waves.',
            'Windsurfing is a challenging water activity. Ride the winds and glide on the water.',
            'Kiteboarding is an exciting combination of kite flying and surfing. Try it for an adrenaline rush.',
            'Water aerobics is a refreshing way to stay fit. Enjoy a workout in the pool.',
            'Scuba diving is an underwater adventure. Explore the depths and discover marine life.',
            'Tubing behind a boat is a thrilling water activity. Hold on tight for an exciting ride.',
            'Rowing in the sunshine is a peaceful outdoor activity. Enjoy the rhythmic motion on calm waters.',
            'Fishing in warm weather is relaxing. Cast your line and enjoy the tranquility.',
            'Hiking in moderate temperatures is enjoyable. Explore trails and connect with nature.',
            'Cycling in the sunshine is a great way to stay active. Enjoy the scenery on a bike ride.',
            'Running in warm weather is invigorating. Break a sweat and enjoy the fresh air.',
            'Volleyball on the beach is a great way to stay active. Feel the sand between your toes.',
            'Soccer on a sunny day is a lively and fun activity. Kick the ball around with friends.',
            'Tennis is a fantastic sport in warm weather. Grab a racket and hit the court.',
            'Outdoor yoga classes in the park are rejuvenating. Connect with nature and find inner peace.',
            'Pilates in the sunshine is perfect for toning muscles. Enjoy a session outdoors.',
            'Fitness classes in the open air are invigorating. Join a class and stay fit in the sun.',
            'Rock climbing in warm weather is a thrilling outdoor activity. Challenge yourself on the rocks.',
            'Trail running in the sunshine is invigorating. Enjoy the trails and the warm weather.',
            'Mountain biking is a thrilling outdoor activity. Navigate challenging terrains and enjoy the ride.',
            'Camping in warm weather is a delightful experience. Enjoy the outdoors under the stars.',
            'Picnicking in pleasant temperatures is relaxing. Pack a meal and enjoy nature.',
            'Outdoor concerts are enjoyable in warm weather. Listen to music under the open sky.',
            'Festivals in the sunshine are lively and fun. Join the celebration and have a great time.',
            'Fishing trips in sunny weather are enjoyable. Cast your line and enjoy the great outdoors.',
            'Bird watching in warm weather is delightful. Spot different species and enjoy nature.',
            'Nature photography in the sunshine is rewarding. Capture the beauty of the outdoors.',
            'Geocaching is an adventurous outdoor activity. Go on a treasure hunt with your GPS!',
            'Stand-up paddleboarding is a great way to stay active on calm waters. Enjoy the sunshine.',
            'Beachcombing is a relaxing beach activity. Stroll along the shore and discover treasures.',
            'Lawn games in the warm weather are fun. Play classics like bocce or cornhole.',
            'Outdoor cooking classes are enjoyable in pleasant temperatures. Learn new recipes and have fun.',
            'Beer tasting events in the sunshine are festive. Sample seasonal brews and enjoy the weather.',
            'Sunset watching is peaceful in warm weather. Find a scenic spot and enjoy the view.',
        ];
    }

    public function getMessagesRainyWeather(): array
    {
        return [
            'Embrace the rain with a jog in the rain-soaked park. It can be a refreshing experience!',
            'Indoor sports like table tennis or badminton are perfect for a rainy day. Stay active indoors!',
            'Challenge yourself with a rock climbing session at an indoor climbing gym on a rainy day.',
            'Join a local trampoline park for some indoor bouncing fun on a rainy day.',
            'Gather friends for a bowling night. It’s a fun and social indoor activity.',
            'Engage in a game of indoor basketball at a local sports facility when the weather is gloomy.',
            'Volleyball can be played indoors as well. Organize an indoor game with friends.',
            'Swimming is not just for sunny days. Head to an indoor pool and enjoy a swim in the rain.',
            'Squash or judo classes are great for staying active indoors during rainy weather.',
            'Explore the world of karate with indoor sessions. It’s a fantastic way to learn self-defense.',
            'Organize an indoor soccer match with friends. Stay active and have fun regardless of the weather.',
            'Join an indoor cycling class for a high-energy workout without worrying about the rain.',
            'Pamper yourself with a spa day. Relax and rejuvenate indoors during the rainy weather.',
            'Discover the joy of reading a good book. Rainy days are perfect for cozying up with a novel.',
            'Try your hand at indoor gardening. Bring some greenery into your home during the rainy season.',
            'Cook up a storm in the kitchen. Experiment with new recipes on a rainy day.',
            'Challenge friends to a board game marathon. It’s a great way to spend a rainy afternoon.',
            'Host a movie marathon at home. Pick your favorite films and enjoy a cozy day indoors.',
            'Learn a new musical instrument. Rainy days provide a perfect opportunity for indoor practice.',
            'Start a DIY home improvement project. Tackle that indoor project you’ve been putting off.',
            'Indulge in a puzzle-solving session. Jigsaw puzzles or brain teasers are great for rainy days.',
            'Take a virtual workout class. Many fitness classes are available online for rainy days.',
            'Plan a cozy indoor picnic with your favorite snacks. Rainy days can be delightful indoors.',
            'Visit a local museum or art gallery. Rainy weather is perfect for exploring cultural venues.',
            'Attend a cooking or baking class. Learn new culinary skills indoors during the rain.',
            'Join a virtual fitness challenge. Stay motivated with online challenges on rainy days.',
            'Explore the world of online gaming. Rainy days can be perfect for a gaming marathon.',
            'Host a virtual trivia night with friends. Test your knowledge from the comfort of your home.',
            'Try your hand at indoor photography. Capture the beauty of everyday moments indoors.',
            'Take a virtual tour of historical sites or landmarks. Explore the world without leaving home.',
            'Engage in a virtual art class. Learn to draw or paint from the comfort of your living room.',
            'Start a journal or blog. Document your thoughts and experiences during the rainy season.',
            'Join a virtual dance class. Stay active and learn new dance moves indoors.',
            'Practice mindfulness with meditation or yoga. Rainy days provide a peaceful atmosphere.',
            'Create a rainy day playlist. Enjoy your favorite music while listening to the sound of rain.',
            'Visit an indoor botanical garden. Explore diverse plant life without getting wet.',
            'Attend a virtual concert or live-streamed performance. Enjoy the arts from home.',
            'Experiment with indoor photography. Capture the unique atmosphere of rainy days.',
            'Take an online language course. Use rainy days to enhance your language skills.',
            'Attend a virtual book club. Discuss literature with fellow book enthusiasts online.',
            'Start a DIY home decor project. Get creative and give your home a rainy-day makeover.',
            'Participate in a virtual escape room. Solve puzzles and mysteries from the comfort of your home.',
            'Explore online cooking classes. Learn new culinary techniques and recipes indoors.',
            'Take a virtual tour of famous landmarks around the world. Experience global culture from home.',
            'Join an online workout challenge. Stay active and motivated with virtual fitness goals.',
            'Engage in virtual board games with friends. Connect and have fun without leaving home.',
        ];
    }

    public function getMessagesFromThirtyDegrees(): array{
        return [
            "Enjoy the sunshine and go for a refreshing swim!",
            "Stay active and take a hike in the beautiful weather.",
            "Embrace the heat and try outdoor yoga for a change.",
            "Grab your bike and explore the city in the warm weather.",
            "Beat the heat by playing beach volleyball with friends.",
            "Make the most of the hot weather and go for a run.",
            "Take advantage of the sunshine and have a picnic in the park.",
            "Try your hand at outdoor sports like tennis or badminton.",
            "Stay cool by going kayaking or paddleboarding on a lake.",
            "Join a local sports league and play your favorite game outside.",
            "Get your adrenaline pumping with some outdoor rock climbing.",
            "Take a leisurely bike ride along scenic trails.",
            "Enjoy the warmth and have a game of frisbee in the park.",
            "Embrace the rain with a jog in the rain-soaked park. It can be a refreshing experience!",
            "Indoor sports like table tennis or badminton are perfect for a rainy day. Stay active indoors!",
            "Challenge yourself with a rock climbing session at an indoor climbing gym on a rainy day.",
            "Join a local trampoline park for some indoor bouncing fun on a rainy day.",
            "Gather friends for a bowling night. It’s a fun and social indoor activity.",
            "Engage in a game of indoor basketball at a local sports facility when the weather is gloomy.",
            "Volleyball can be played indoors as well. Organize an indoor game with friends.",
            "Swimming is not just for sunny days. Head to an indoor pool and enjoy a swim in the rain.",
            "Squash or judo classes are great for staying active indoors during rainy weather.",
            "Explore the world of karate with indoor sessions. It’s a fantastic way to learn self-defense.",
            "Organize an indoor soccer match with friends. Stay active and have fun regardless of the weather.",
            "Join an indoor cycling class for a high-energy workout without worrying about the rain.",
            "Pamper yourself with a spa day. Relax and rejuvenate indoors during the rainy weather.",
            "Discover the joy of reading a good book. Rainy days are perfect for cozying up with a novel.",
            "Try your hand at indoor gardening. Bring some greenery into your home during the rainy season.",
            "Cook up a storm in the kitchen. Experiment with new recipes on a rainy day.",
            "Challenge friends to a board game marathon. It’s a great way to spend a rainy afternoon.",
            "Host a movie marathon at home. Pick your favorite films and enjoy a cozy day indoors.",
            "Learn a new musical instrument. Rainy days provide a perfect opportunity for indoor practice.",
            "Start a DIY home improvement project. Tackle that indoor project you’ve been putting off.",
            "Indulge in a puzzle-solving session. Jigsaw puzzles or brain teasers are great for rainy days.",
            "Take a virtual workout class. Many fitness classes are available online for rainy days.",
            "Plan a cozy indoor picnic with your favorite snacks. Rainy days can be delightful indoors.",
            "Visit a local museum or art gallery. Rainy weather is perfect for exploring cultural venues.",
            "Attend a cooking or baking class. Learn new culinary skills indoors during the rain.",
            "Join a virtual fitness challenge. Stay motivated with online challenges on rainy days.",
            "Explore the world of online gaming. Rainy days can be perfect for a gaming marathon.",
            "Host a virtual trivia night with friends. Test your knowledge from the comfort of your home.",
            "Try your hand at indoor photography. Capture the beauty of everyday moments indoors.",
            "Take a virtual tour of historical sites or landmarks. Explore the world without leaving home.",
            "Engage in a virtual art class. Learn to draw or paint from the comfort of your living room.",
            "Start a journal or blog. Document your thoughts and experiences during the rainy season.",
            "Join a virtual dance class. Stay active and learn new dance moves indoors.",
            "Practice mindfulness with meditation or yoga. Rainy days provide a peaceful atmosphere.",
            "Create a rainy day playlist. Enjoy your favorite music while listening to the sound of rain.",
            "Visit an indoor botanical garden. Explore diverse plant life without getting wet.",
            "Attend a virtual concert or live-streamed performance. Enjoy the arts from home.",
            "Experiment with indoor photography. Capture the unique atmosphere of rainy days.",
            "Take an online language course. Use rainy days to enhance your language skills.",
            "Attend a virtual book club. Discuss literature with fellow book enthusiasts online.",
            "Start a DIY home decor project. Get creative and give your home a rainy-day makeover.",
            "Participate in a virtual escape room. Solve puzzles and mysteries from the comfort of your home.",
            "Explore online cooking classes. Learn new culinary techniques and recipes indoors.",
            "Take a virtual tour of famous landmarks around the world. Experience global culture from home.",
            "Join an online workout challenge. Stay active and motivated with virtual fitness goals.",
            "Engage in virtual board games with friends. Connect and have fun without leaving home.",
        ];
    }

}
